//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksDW2012 {

    public partial class frmdbo_DimEmployee {

        ///<summary>
    	///ScriptManager1 control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.ToolkitScriptManager ScriptManager1;
        
        /// <summary>
        /// ec control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdventureWorksDW2012.Library.UserControls_OKMessageBox ec;
        
    	///<summary>
    	///lblTitle control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblTitle;

    	///<summary>
    	///lblMode control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblMode;

    	///<summary>
	///pnlGrid control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlGrid;
        
        /// <summary>
        /// cmbFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cmbFields;
        
        /// <summary>
        /// cmbCondition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cmbCondition;
        
        /// <summary>
        /// txtSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        
        /// <summary>
        /// butSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button butSearch;
        
        /// <summary>
        /// butShowAll control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button butShowAll;

        /// <summary>
        /// ddlFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlFile; 

        /// <summary>
        /// btnExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnExport;

    	///<summary>
    	///btnAddNew control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button btnAddNew;

    	///<summary>
    	///cmbRecords control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DropDownList cmbRecords;

    	///<summary>
    	///butRecords control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butRecords;

    	///<summary>
    	///grddbo_DimEmployee control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DataGrid grddbo_DimEmployee;

    	///<summary>
    	///htmlHiddenSortExpression control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.HtmlControls.HtmlInputHidden htmlHiddenSortExpression;

    	///<summary>
    	///pnlDelete control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlDelete;

    	///<summary>
    	///lblDelete control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblDelete;

    	///<summary>
    	///butYes control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butYes;

    	///<summary>
    	///butNo control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butNo;

    	///<summary>
    	///pnlForm control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlForm;

    	///<summary>
    	///txtEmployeeKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEmployeeKey;

    	///<summary>
    	///revEmployeeKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmployeeKey;

    	///<summary>
    	///txtParentEmployeeKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DropDownList txtParentEmployeeKey;

    	///<summary>
    	///txtEmployeeNationalIDAlternateKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEmployeeNationalIDAlternateKey;

    	///<summary>
    	///txtParentEmployeeNationalIDAlternateKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtParentEmployeeNationalIDAlternateKey;

    	///<summary>
    	///txtSalesTerritoryKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DropDownList txtSalesTerritoryKey;

    	///<summary>
    	///txtFirstName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFirstName;

    	///<summary>
    	///txtLastName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtLastName;

    	///<summary>
    	///txtMiddleName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtMiddleName;

    	///<summary>
    	///txtNameStyle control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.CheckBox txtNameStyle;

    	///<summary>
    	///txtTitle control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtTitle;

    	///<summary>
    	///txtHireDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtHireDate;

    	///<summary>
    	///ImageHireDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.ImageButton ImageHireDate;

    	///<summary>
    	///calendarButtonExtenderHireDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.CalendarExtender calendarButtonExtenderHireDate;

    	///<summary>
    	///txtBirthDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtBirthDate;

    	///<summary>
    	///ImageBirthDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.ImageButton ImageBirthDate;

    	///<summary>
    	///calendarButtonExtenderBirthDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.CalendarExtender calendarButtonExtenderBirthDate;

    	///<summary>
    	///txtLoginID control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtLoginID;

    	///<summary>
    	///txtEmailAddress control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEmailAddress;

    	///<summary>
    	///txtPhone control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtPhone;

    	///<summary>
    	///txtMaritalStatus control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtMaritalStatus;

    	///<summary>
    	///txtEmergencyContactName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEmergencyContactName;

    	///<summary>
    	///txtEmergencyContactPhone control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEmergencyContactPhone;

    	///<summary>
    	///txtSalariedFlag control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.CheckBox txtSalariedFlag;

    	///<summary>
    	///txtGender control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtGender;

    	///<summary>
    	///txtPayFrequency control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtPayFrequency;

    	///<summary>
    	///revPayFrequency control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revPayFrequency;

    	///<summary>
    	///txtBaseRate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtBaseRate;

    	///<summary>
    	///revBaseRate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revBaseRate;

    	///<summary>
    	///txtVacationHours control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtVacationHours;

    	///<summary>
    	///revVacationHours control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revVacationHours;

    	///<summary>
    	///txtSickLeaveHours control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtSickLeaveHours;

    	///<summary>
    	///revSickLeaveHours control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revSickLeaveHours;

    	///<summary>
    	///txtCurrentFlag control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.CheckBox txtCurrentFlag;

    	///<summary>
    	///txtSalesPersonFlag control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.CheckBox txtSalesPersonFlag;

    	///<summary>
    	///txtDepartmentName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtDepartmentName;

    	///<summary>
    	///txtStartDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtStartDate;

    	///<summary>
    	///ImageStartDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.ImageButton ImageStartDate;

    	///<summary>
    	///calendarButtonExtenderStartDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.CalendarExtender calendarButtonExtenderStartDate;

    	///<summary>
    	///txtEndDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEndDate;

    	///<summary>
    	///ImageEndDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.ImageButton ImageEndDate;

    	///<summary>
    	///calendarButtonExtenderEndDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.CalendarExtender calendarButtonExtenderEndDate;

    	///<summary>
    	///txtStatus control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtStatus;

    	///<summary>
    	///pnlSave control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlSave;

    	///<summary>
    	///butCancel control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butCancel;

    	///<summary>
    	///btnSave control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button btnSave;

    	///<summary>
    	///pnlMessage control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlMessage;

    	///<summary>
    	///lblMessage control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblMessage;

    	///<summary>
    	///butOK control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butOK;
    }
}

 
