//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksDW2012 {

    public partial class frmdbo_DimDate {

        ///<summary>
    	///ScriptManager1 control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.ToolkitScriptManager ScriptManager1;
        
        /// <summary>
        /// ec control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdventureWorksDW2012.Library.UserControls_OKMessageBox ec;
        
    	///<summary>
    	///lblTitle control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblTitle;

    	///<summary>
    	///lblMode control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblMode;

    	///<summary>
	///pnlGrid control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlGrid;
        
        /// <summary>
        /// cmbFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cmbFields;
        
        /// <summary>
        /// cmbCondition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cmbCondition;
        
        /// <summary>
        /// txtSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        
        /// <summary>
        /// butSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button butSearch;
        
        /// <summary>
        /// butShowAll control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button butShowAll;

        /// <summary>
        /// ddlFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlFile; 

        /// <summary>
        /// btnExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnExport;

    	///<summary>
    	///btnAddNew control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button btnAddNew;

    	///<summary>
    	///cmbRecords control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DropDownList cmbRecords;

    	///<summary>
    	///butRecords control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butRecords;

    	///<summary>
    	///grddbo_DimDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DataGrid grddbo_DimDate;

    	///<summary>
    	///htmlHiddenSortExpression control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.HtmlControls.HtmlInputHidden htmlHiddenSortExpression;

    	///<summary>
    	///pnlDelete control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlDelete;

    	///<summary>
    	///lblDelete control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblDelete;

    	///<summary>
    	///butYes control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butYes;

    	///<summary>
    	///butNo control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butNo;

    	///<summary>
    	///pnlForm control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlForm;

    	///<summary>
    	///txtDateKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtDateKey;

    	///<summary>
    	///revDateKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revDateKey;

    	///<summary>
    	///txtFullDateAlternateKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFullDateAlternateKey;

    	///<summary>
    	///ImageFullDateAlternateKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.ImageButton ImageFullDateAlternateKey;

    	///<summary>
    	///calendarButtonExtenderFullDateAlternateKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.CalendarExtender calendarButtonExtenderFullDateAlternateKey;

    	///<summary>
    	///txtDayNumberOfWeek control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtDayNumberOfWeek;

    	///<summary>
    	///revDayNumberOfWeek control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revDayNumberOfWeek;

    	///<summary>
    	///txtEnglishDayNameOfWeek control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEnglishDayNameOfWeek;

    	///<summary>
    	///txtSpanishDayNameOfWeek control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtSpanishDayNameOfWeek;

    	///<summary>
    	///txtFrenchDayNameOfWeek control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFrenchDayNameOfWeek;

    	///<summary>
    	///txtDayNumberOfMonth control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtDayNumberOfMonth;

    	///<summary>
    	///revDayNumberOfMonth control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revDayNumberOfMonth;

    	///<summary>
    	///txtDayNumberOfYear control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtDayNumberOfYear;

    	///<summary>
    	///revDayNumberOfYear control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revDayNumberOfYear;

    	///<summary>
    	///txtWeekNumberOfYear control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtWeekNumberOfYear;

    	///<summary>
    	///revWeekNumberOfYear control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revWeekNumberOfYear;

    	///<summary>
    	///txtEnglishMonthName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEnglishMonthName;

    	///<summary>
    	///txtSpanishMonthName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtSpanishMonthName;

    	///<summary>
    	///txtFrenchMonthName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFrenchMonthName;

    	///<summary>
    	///txtMonthNumberOfYear control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtMonthNumberOfYear;

    	///<summary>
    	///revMonthNumberOfYear control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revMonthNumberOfYear;

    	///<summary>
    	///txtCalendarQuarter control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtCalendarQuarter;

    	///<summary>
    	///revCalendarQuarter control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revCalendarQuarter;

    	///<summary>
    	///txtCalendarYear control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtCalendarYear;

    	///<summary>
    	///revCalendarYear control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revCalendarYear;

    	///<summary>
    	///txtCalendarSemester control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtCalendarSemester;

    	///<summary>
    	///revCalendarSemester control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revCalendarSemester;

    	///<summary>
    	///txtFiscalQuarter control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFiscalQuarter;

    	///<summary>
    	///revFiscalQuarter control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revFiscalQuarter;

    	///<summary>
    	///txtFiscalYear control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFiscalYear;

    	///<summary>
    	///revFiscalYear control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revFiscalYear;

    	///<summary>
    	///txtFiscalSemester control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFiscalSemester;

    	///<summary>
    	///revFiscalSemester control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revFiscalSemester;

    	///<summary>
    	///pnlSave control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlSave;

    	///<summary>
    	///butCancel control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butCancel;

    	///<summary>
    	///btnSave control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button btnSave;

    	///<summary>
    	///pnlMessage control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlMessage;

    	///<summary>
    	///lblMessage control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblMessage;

    	///<summary>
    	///butOK control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butOK;
    }
}

 
