//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksDW2012 {

    public partial class frmdbo_DimCustomer {

        ///<summary>
    	///ScriptManager1 control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.ToolkitScriptManager ScriptManager1;
        
        /// <summary>
        /// ec control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdventureWorksDW2012.Library.UserControls_OKMessageBox ec;
        
    	///<summary>
    	///lblTitle control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblTitle;

    	///<summary>
    	///lblMode control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblMode;

    	///<summary>
	///pnlGrid control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlGrid;
        
        /// <summary>
        /// cmbFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cmbFields;
        
        /// <summary>
        /// cmbCondition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cmbCondition;
        
        /// <summary>
        /// txtSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        
        /// <summary>
        /// butSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button butSearch;
        
        /// <summary>
        /// butShowAll control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button butShowAll;

        /// <summary>
        /// ddlFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlFile; 

        /// <summary>
        /// btnExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnExport;

    	///<summary>
    	///btnAddNew control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button btnAddNew;

    	///<summary>
    	///cmbRecords control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DropDownList cmbRecords;

    	///<summary>
    	///butRecords control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butRecords;

    	///<summary>
    	///grddbo_DimCustomer control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DataGrid grddbo_DimCustomer;

    	///<summary>
    	///htmlHiddenSortExpression control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.HtmlControls.HtmlInputHidden htmlHiddenSortExpression;

    	///<summary>
    	///pnlDelete control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlDelete;

    	///<summary>
    	///lblDelete control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblDelete;

    	///<summary>
    	///butYes control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butYes;

    	///<summary>
    	///butNo control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butNo;

    	///<summary>
    	///pnlForm control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlForm;

    	///<summary>
    	///txtCustomerKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtCustomerKey;

    	///<summary>
    	///revCustomerKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revCustomerKey;

    	///<summary>
    	///txtGeographyKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DropDownList txtGeographyKey;

    	///<summary>
    	///txtCustomerAlternateKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtCustomerAlternateKey;

    	///<summary>
    	///txtTitle control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtTitle;

    	///<summary>
    	///txtFirstName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFirstName;

    	///<summary>
    	///txtMiddleName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtMiddleName;

    	///<summary>
    	///txtLastName control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtLastName;

    	///<summary>
    	///txtNameStyle control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.CheckBox txtNameStyle;

    	///<summary>
    	///txtBirthDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtBirthDate;

    	///<summary>
    	///ImageBirthDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.ImageButton ImageBirthDate;

    	///<summary>
    	///calendarButtonExtenderBirthDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.CalendarExtender calendarButtonExtenderBirthDate;

    	///<summary>
    	///txtMaritalStatus control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtMaritalStatus;

    	///<summary>
    	///txtSuffix control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtSuffix;

    	///<summary>
    	///txtGender control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtGender;

    	///<summary>
    	///txtEmailAddress control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEmailAddress;

    	///<summary>
    	///txtYearlyIncome control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtYearlyIncome;

    	///<summary>
    	///revYearlyIncome control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revYearlyIncome;

    	///<summary>
    	///txtTotalChildren control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtTotalChildren;

    	///<summary>
    	///revTotalChildren control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revTotalChildren;

    	///<summary>
    	///txtNumberChildrenAtHome control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtNumberChildrenAtHome;

    	///<summary>
    	///revNumberChildrenAtHome control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revNumberChildrenAtHome;

    	///<summary>
    	///txtEnglishEducation control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEnglishEducation;

    	///<summary>
    	///txtSpanishEducation control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtSpanishEducation;

    	///<summary>
    	///txtFrenchEducation control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFrenchEducation;

    	///<summary>
    	///txtEnglishOccupation control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtEnglishOccupation;

    	///<summary>
    	///txtSpanishOccupation control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtSpanishOccupation;

    	///<summary>
    	///txtFrenchOccupation control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFrenchOccupation;

    	///<summary>
    	///txtHouseOwnerFlag control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtHouseOwnerFlag;

    	///<summary>
    	///txtNumberCarsOwned control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtNumberCarsOwned;

    	///<summary>
    	///revNumberCarsOwned control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revNumberCarsOwned;

    	///<summary>
    	///txtAddressLine1 control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtAddressLine1;

    	///<summary>
    	///txtAddressLine2 control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtAddressLine2;

    	///<summary>
    	///txtPhone control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtPhone;

    	///<summary>
    	///txtDateFirstPurchase control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtDateFirstPurchase;

    	///<summary>
    	///ImageDateFirstPurchase control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.ImageButton ImageDateFirstPurchase;

    	///<summary>
    	///calendarButtonExtenderDateFirstPurchase control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.CalendarExtender calendarButtonExtenderDateFirstPurchase;

    	///<summary>
    	///txtCommuteDistance control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtCommuteDistance;

    	///<summary>
    	///pnlSave control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlSave;

    	///<summary>
    	///butCancel control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butCancel;

    	///<summary>
    	///btnSave control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button btnSave;

    	///<summary>
    	///pnlMessage control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlMessage;

    	///<summary>
    	///lblMessage control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblMessage;

    	///<summary>
    	///butOK control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butOK;
    }
}

 
