//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksDW2012 {

    public partial class frmdbo_FactCallCenter {

        ///<summary>
    	///ScriptManager1 control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.ToolkitScriptManager ScriptManager1;
        
        /// <summary>
        /// ec control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdventureWorksDW2012.Library.UserControls_OKMessageBox ec;
        
    	///<summary>
    	///lblTitle control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblTitle;

    	///<summary>
    	///lblMode control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblMode;

    	///<summary>
	///pnlGrid control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlGrid;
        
        /// <summary>
        /// cmbFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cmbFields;
        
        /// <summary>
        /// cmbCondition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cmbCondition;
        
        /// <summary>
        /// txtSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        
        /// <summary>
        /// butSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button butSearch;
        
        /// <summary>
        /// butShowAll control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button butShowAll;

        /// <summary>
        /// ddlFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlFile; 

        /// <summary>
        /// btnExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnExport;

    	///<summary>
    	///btnAddNew control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button btnAddNew;

    	///<summary>
    	///cmbRecords control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DropDownList cmbRecords;

    	///<summary>
    	///butRecords control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butRecords;

    	///<summary>
    	///grddbo_FactCallCenter control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DataGrid grddbo_FactCallCenter;

    	///<summary>
    	///htmlHiddenSortExpression control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.HtmlControls.HtmlInputHidden htmlHiddenSortExpression;

    	///<summary>
    	///pnlDelete control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlDelete;

    	///<summary>
    	///lblDelete control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblDelete;

    	///<summary>
    	///butYes control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butYes;

    	///<summary>
    	///butNo control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butNo;

    	///<summary>
    	///pnlForm control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlForm;

    	///<summary>
    	///txtFactCallCenterID control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtFactCallCenterID;

    	///<summary>
    	///revFactCallCenterID control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revFactCallCenterID;

    	///<summary>
    	///txtDateKey control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.DropDownList txtDateKey;

    	///<summary>
    	///txtWageType control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtWageType;

    	///<summary>
    	///txtShift control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtShift;

    	///<summary>
    	///txtLevelOneOperators control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtLevelOneOperators;

    	///<summary>
    	///revLevelOneOperators control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revLevelOneOperators;

    	///<summary>
    	///txtLevelTwoOperators control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtLevelTwoOperators;

    	///<summary>
    	///revLevelTwoOperators control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revLevelTwoOperators;

    	///<summary>
    	///txtTotalOperators control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtTotalOperators;

    	///<summary>
    	///revTotalOperators control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revTotalOperators;

    	///<summary>
    	///txtCalls control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtCalls;

    	///<summary>
    	///revCalls control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revCalls;

    	///<summary>
    	///txtAutomaticResponses control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtAutomaticResponses;

    	///<summary>
    	///revAutomaticResponses control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revAutomaticResponses;

    	///<summary>
    	///txtOrders control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtOrders;

    	///<summary>
    	///revOrders control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revOrders;

    	///<summary>
    	///txtIssuesRaised control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtIssuesRaised;

    	///<summary>
    	///revIssuesRaised control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revIssuesRaised;

    	///<summary>
    	///txtAverageTimePerIssue control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtAverageTimePerIssue;

    	///<summary>
    	///revAverageTimePerIssue control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revAverageTimePerIssue;

    	///<summary>
    	///txtServiceGrade control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtServiceGrade;

    	///<summary>
    	///revServiceGrade control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.RegularExpressionValidator revServiceGrade;

    	///<summary>
    	///txtDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.TextBox txtDate;

    	///<summary>
    	///ImageDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.ImageButton ImageDate;

    	///<summary>
    	///calendarButtonExtenderDate control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::AjaxControlToolkit.CalendarExtender calendarButtonExtenderDate;

    	///<summary>
    	///pnlSave control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlSave;

    	///<summary>
    	///butCancel control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butCancel;

    	///<summary>
    	///btnSave control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button btnSave;

    	///<summary>
    	///pnlMessage control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Panel pnlMessage;

    	///<summary>
    	///lblMessage control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Label lblMessage;

    	///<summary>
    	///butOK control.
    	///</summary>
    	///<remarks>
    	///Auto-generated field.
    	///To modify move field declaration from designer file to code-behind file.
    	///</remarks>
    	protected global::System.Web.UI.WebControls.Button butOK;
    }
}

 
